### ISSUE TITLE
some change and didn t work anymore

### ISSUE THREAD

**Issue by alsg67** [GamerHack/ps4jb702#1]
Hello
I dont know if im alone but today i did see some minor change on the page, and the jailbreak doesnt work anymore
Thanks for your concern and work  
And please excuse my englush, im french not at ease

**Comment by GamerHack** [comment]
It's been a while since I stopped supporting individual repositories like this, but I never made any changes to make them stop working, so I don't understand, you have to go to my main repository where all the updated hosts are:

GamerHack.github.io

I recommend that you visit my Twitter since I made these changes a long time ago, greetings.

**Comment by GamerHack** [comment]
It's been a while since I stopped supporting individual repositories like this, but I never made any changes to make them stop working, so I don't understand, you have to go to my main repository where all the updated hosts are:

gamerhack.github.io

I recommend that you visit my Twitter since I made these changes a long time ago, greetings.

**Comment by alsg67** [comment]
Ok thank you for your reply, I dont unserdtand myself, but a did try to more 100 x, still don t work
I dont mean to bother you more
I will look the links that you gave me
Goodbye
________________________________
De : GamerHack ***@***.***>
Envoyé : jeudi 23 février 2023 15:25
À : GamerHack/ps4jb702 ***@***.***>
Cc : alsg67 ***@***.***>; Author ***@***.***>
Objet : Re: [GamerHack/ps4jb702] some change and didn t work anymore (Issue #1)


It's been a while since I stopped supporting individual repositories like this, but I never made any changes to make them stop working, so I don't understand, you have to go to my main repository where all the updated hosts are:

gamerhack.github.io

I recommend that you visit my Twitter since I made these changes a long time ago, greetings.
